
/******************************************************************************
 ******************** DDL and population data scripts *************************
 ******************************************************************************/

-- Creating database
DROP DATABASE expedia_recommendations;
CREATE DATABASE IF NOT EXISTS expedia_recommendations 
COMMENT 'Database for expedia_recommendations files';


/***************************** sample_submission ******************************/

-- Creating staging table based on data in files of user location 
DROP TABLE expedia_recommendations.tmp_sample_submission;
CREATE EXTERNAL TABLE tmp_sample_submission (
	id STRING , 
	hotel_cluster STRING)
  STORED AS PARQUET
    LOCATION '/user/kl/expedia-hotel-recommendations-parquet/sample-submission.parquet';

-- Creating destination table of sample submissions
DROP TABLE expedia_recommendations.sample_submission;
CREATE TABLE expedia_recommendations.sample_submission (
	id INT , 
	hotel_cluster STRING);

-- Inserting data by overwriting existing data if any
INSERT OVERWRITE TABLE expedia_recommendations.sample_submission
SELECT * FROM expedia_recommendations.tmp_sample_submission
;
 
/***************************** destination ******************************/

-- Creating staging table based on data in files of user location 
DROP TABLE expedia_recommendations.tmp_destination;
CREATE EXTERNAL TABLE tmp_destination (
srch_destination_id STRING,
d1 STRING,
d2 STRING,
d3 STRING,
d4 STRING,
d5 STRING,
d6 STRING,
d7 STRING,
d8 STRING,
d9 STRING,
d10 STRING,
d11 STRING,
d12 STRING,
d13 STRING,
d14 STRING,
d15 STRING,
d16 STRING,
d17 STRING,
d18 STRING,
d19 STRING,
d20 STRING,
d21 STRING,
d22 STRING,
d23 STRING,
d24 STRING,
d25 STRING,
d26 STRING,
d27 STRING,
d28 STRING,
d29 STRING,
d30 STRING,
d31 STRING,
d32 STRING,
d33 STRING,
d34 STRING,
d35 STRING,
d36 STRING,
d37 STRING,
d38 STRING,
d39 STRING,
d40 STRING,
d41 STRING,
d42 STRING,
d43 STRING,
d44 STRING,
d45 STRING,
d46 STRING,
d47 STRING,
d48 STRING,
d49 STRING,
d50 STRING,
d51 STRING,
d52 STRING,
d53 STRING,
d54 STRING,
d55 STRING,
d56 STRING,
d57 STRING,
d58 STRING,
d59 STRING,
d60 STRING,
d61 STRING,
d62 STRING,
d63 STRING,
d64 STRING,
d65 STRING,
d66 STRING,
d67 STRING,
d68 STRING,
d69 STRING,
d70 STRING,
d71 STRING,
d72 STRING,
d73 STRING,
d74 STRING,
d75 STRING,
d76 STRING,
d77 STRING,
d78 STRING,
d79 STRING,
d80 STRING,
d81 STRING,
d82 STRING,
d83 STRING,
d84 STRING,
d85 STRING,
d86 STRING,
d87 STRING,
d88 STRING,
d89 STRING,
d90 STRING,
d91 STRING,
d92 STRING,
d93 STRING,
d94 STRING,
d95 STRING,
d96 STRING,
d97 STRING,
d98 STRING,
d99 STRING,
d100 STRING,
d101 STRING,
d102 STRING,
d103 STRING,
d104 STRING,
d105 STRING,
d106 STRING,
d107 STRING,
d108 STRING,
d109 STRING,
d110 STRING,
d111 STRING,
d112 STRING,
d113 STRING,
d114 STRING,
d115 STRING,
d116 STRING,
d117 STRING,
d118 STRING,
d119 STRING,
d120 STRING,
d121 STRING,
d122 STRING,
d123 STRING,
d124 STRING,
d125 STRING,
d126 STRING,
d127 STRING,
d128 STRING,
d129 STRING,
d130 STRING,
d131 STRING,
d132 STRING,
d133 STRING,
d134 STRING,
d135 STRING,
d136 STRING,
d137 STRING,
d138 STRING,
d139 STRING,
d140 STRING,
d141 STRING,
d142 STRING,
d143 STRING,
d144 STRING,
d145 STRING,
d146 STRING,
d147 STRING,
d148 STRING,
d149 STRING
)
  STORED AS PARQUET
    LOCATION '/user/kl/expedia-hotel-recommendations-parquet/destiantions.parquet';

 -- Creating destination table of destinations
DROP TABLE expedia_recommendations.destination;
CREATE TABLE expedia_recommendations.destination (
srch_destination_id INT,
d1 DOUBLE,
d2 DOUBLE,
d3 DOUBLE,
d4 DOUBLE,
d5 DOUBLE,
d6 DOUBLE,
d7 DOUBLE,
d8 DOUBLE,
d9 DOUBLE,
d10 DOUBLE,
d11 DOUBLE,
d12 DOUBLE,
d13 DOUBLE,
d14 DOUBLE,
d15 DOUBLE,
d16 DOUBLE,
d17 DOUBLE,
d18 DOUBLE,
d19 DOUBLE,
d20 DOUBLE,
d21 DOUBLE,
d22 DOUBLE,
d23 DOUBLE,
d24 DOUBLE,
d25 DOUBLE,
d26 DOUBLE,
d27 DOUBLE,
d28 DOUBLE,
d29 DOUBLE,
d30 DOUBLE,
d31 DOUBLE,
d32 DOUBLE,
d33 DOUBLE,
d34 DOUBLE,
d35 DOUBLE,
d36 DOUBLE,
d37 DOUBLE,
d38 DOUBLE,
d39 DOUBLE,
d40 DOUBLE,
d41 DOUBLE,
d42 DOUBLE,
d43 DOUBLE,
d44 DOUBLE,
d45 DOUBLE,
d46 DOUBLE,
d47 DOUBLE,
d48 DOUBLE,
d49 DOUBLE,
d50 DOUBLE,
d51 DOUBLE,
d52 DOUBLE,
d53 DOUBLE,
d54 DOUBLE,
d55 DOUBLE,
d56 DOUBLE,
d57 DOUBLE,
d58 DOUBLE,
d59 DOUBLE,
d60 DOUBLE,
d61 DOUBLE,
d62 DOUBLE,
d63 DOUBLE,
d64 DOUBLE,
d65 DOUBLE,
d66 DOUBLE,
d67 DOUBLE,
d68 DOUBLE,
d69 DOUBLE,
d70 DOUBLE,
d71 DOUBLE,
d72 DOUBLE,
d73 DOUBLE,
d74 DOUBLE,
d75 DOUBLE,
d76 DOUBLE,
d77 DOUBLE,
d78 DOUBLE,
d79 DOUBLE,
d80 DOUBLE,
d81 DOUBLE,
d82 DOUBLE,
d83 DOUBLE,
d84 DOUBLE,
d85 DOUBLE,
d86 DOUBLE,
d87 DOUBLE,
d88 DOUBLE,
d89 DOUBLE,
d90 DOUBLE,
d91 DOUBLE,
d92 DOUBLE,
d93 DOUBLE,
d94 DOUBLE,
d95 DOUBLE,
d96 DOUBLE,
d97 DOUBLE,
d98 DOUBLE,
d99 DOUBLE,
d100 DOUBLE,
d101 DOUBLE,
d102 DOUBLE,
d103 DOUBLE,
d104 DOUBLE,
d105 DOUBLE,
d106 DOUBLE,
d107 DOUBLE,
d108 DOUBLE,
d109 DOUBLE,
d110 DOUBLE,
d111 DOUBLE,
d112 DOUBLE,
d113 DOUBLE,
d114 DOUBLE,
d115 DOUBLE,
d116 DOUBLE,
d117 DOUBLE,
d118 DOUBLE,
d119 DOUBLE,
d120 DOUBLE,
d121 DOUBLE,
d122 DOUBLE,
d123 DOUBLE,
d124 DOUBLE,
d125 DOUBLE,
d126 DOUBLE,
d127 DOUBLE,
d128 DOUBLE,
d129 DOUBLE,
d130 DOUBLE,
d131 DOUBLE,
d132 DOUBLE,
d133 DOUBLE,
d134 DOUBLE,
d135 DOUBLE,
d136 DOUBLE,
d137 DOUBLE,
d138 DOUBLE,
d139 DOUBLE,
d140 DOUBLE,
d141 DOUBLE,
d142 DOUBLE,
d143 DOUBLE,
d144 DOUBLE,
d145 DOUBLE,
d146 DOUBLE,
d147 DOUBLE,
d148 DOUBLE,
d149 DOUBLE
);

-- Inserting data by overwriting existing data if any
INSERT OVERWRITE TABLE expedia_recommendations.destination
SELECT * FROM expedia_recommendations.tmp_destination
;

/***************************** train ******************************/

-- Creating staging table based on data in files of user location 
DROP TABLE expedia_recommendations.tmp_train;
CREATE EXTERNAL TABLE expedia_recommendations.tmp_train (
date_time STRING,
site_name STRING,
posa_continent STRING,
user_location_country STRING,
user_location_region STRING,
user_location_city STRING,
orig_destination_distance STRING,
user_id STRING,
is_mobile STRING,
is_package STRING,
channel STRING,
srch_ci STRING,
srch_co STRING,
srch_adults_cnt STRING,
srch_children_cnt STRING,
srch_rm_cnt STRING,
srch_destination_id STRING,
srch_destination_type_id STRING,
is_booking STRING,
cnt STRING,
hotel_continent STRING,
hotel_country STRING,
hotel_market STRING,
hotel_cluster STRING
)
  STORED AS PARQUET
    LOCATION '/user/kl/expedia-hotel-recommendations-parquet/train.parquet';

 -- Creating destination table of training data 
DROP TABLE expedia_recommendations.train;  
CREATE TABLE expedia_recommendations.train (
date_time TIMESTAMP,
site_name INT,
posa_continent INT,
user_location_country INT,
user_location_region INT,
user_location_city INT,
orig_destination_distance DOUBLE,
user_id INT,
is_mobile TINYINT,
is_package INT,
channel INT,
srch_ci STRING,
srch_co STRING,
srch_adults_cnt INT,
srch_children_cnt INT,
srch_rm_cnt INT,
srch_destination_id INT,
srch_destination_type_id INT,
is_booking TINYINT,
cnt BIGINT,
hotel_continent INT,
hotel_country INT,
hotel_market INT,
hotel_cluster INT
); 

-- Inserting data by overwriting existing data if any
INSERT OVERWRITE TABLE expedia_recommendations.train 
SELECT * FROM expedia_recommendations.tmp_train;

/***************************** test ******************************/

-- Creating staging table based on data in files of user location 
DROP TABLE expedia_recommendations.tmp_test;
CREATE EXTERNAL TABLE expedia_recommendations.tmp_test (
id STRING,
date_time STRING,
site_name STRING,
posa_continent STRING,
user_location_country STRING,
user_location_region STRING,
user_location_city STRING,
orig_destination_distance STRING,
user_id STRING,
is_mobile STRING,
is_package STRING,
channel STRING,
srch_ci STRING,
srch_co STRING,
srch_adults_cnt STRING,
srch_children_cnt STRING,
srch_rm_cnt STRING,
srch_destination_id STRING,
srch_destination_type_id STRING,
hotel_continent STRING,
hotel_country STRING,
hotel_market STRING
)
  STORED AS PARQUET
    LOCATION '/user/kl/expedia-hotel-recommendations-parquet/test.parquet';

 -- Creating destination table of testing data   
DROP TABLE expedia_recommendations.test;  
CREATE TABLE expedia_recommendations.test (
id INT,
date_time TIMESTAMP,
site_name INT,
posa_continent INT,
user_location_country INT,
user_location_region INT,
user_location_city INT,
orig_destination_distance DOUBLE,
user_id INT,
is_mobile TINYINT,
is_package INT,
channel INT,
srch_ci STRING,
srch_co STRING,
srch_adults_cnt INT,
srch_children_cnt INT,
srch_rm_cnt INT,
srch_destination_id INT,
srch_destination_type_id INT,
hotel_continent INT,
hotel_country INT,
hotel_market INT
);   

-- Inserting data by overwriting existing data if any
INSERT OVERWRITE TABLE expedia_recommendations.test 
SELECT * FROM expedia_recommendations.tmp_test;


